trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: AZURE_CREDENTIALS
    value: $(ARM_SERVICE_PRINCIPAL)

steps:
  - checkout: self

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'YourServiceConnectionName'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)

  - task: UseTerraform@0
    inputs:
      terraformVersion: 'latest'

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform plan -out=plan.tfplan
    displayName: 'Terraform Plan'

  - script: terraform apply plan.tfplan
    displayName: 'Terraform Apply'