name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # ✅ Step 1: Login to Azure using OIDC (NO Client Secret Required)
    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    # ✅ Step 2: Debug Azure Authentication (REMOVE az account show)
    - name: Debug Azure Login
      run: |
        echo "Azure OIDC Login Successful!"
        echo "Checking Environment Variables..."
        env | grep AZURE_

    # ✅ Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # ✅ Step 4: Configure Terraform for OIDC
    - name: Set Terraform Environment Variables
      run: |
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    # ✅ Step 5: Initialize Terraform
    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="resource_group_name=terraform_tfstate_rg" \
          -backend-config="storage_account_name=terraformconfigsa" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate"

    # ✅ Step 6: Plan Terraform Deployment
    - name: Plan Terraform
      run: |
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        terraform plan -out=plan.tfplan

    # ✅ Step 7: Apply Terraform Deployment
    - name: Apply Terraform
      run: |
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        terraform apply -auto-approve plan.tfplan